### ISSUE TITLE
Running code steps

### ISSUE THREAD

**Issue by sunminghao4536** [yininghase/multiagent-collision-mining#1]
Hello, I would like to ask you question.Is adding the collision mining section the next step generated by running generate_test_data.py in https://github.com/yininghase/multi-agent-control？         After running mpc.py in part 4 to get the real trajectory, from https://github.com/yininghase/multi-agent-control Start running train.by, then run inferrence.py, and then run calculate_tetrics.py? thank you

**Comment by yininghase** [comment]
Hello, thanks for your interest in this work. What you mentioned above is generally correct. 

To be specific: 
1. Run generate_test_data.py on 3 to 4 vehicles to get some random scenarios,
2. Run inference.py on these random scenarios with GNN model to get the inference trajectory from GNN. 
3. Run calulate_metrics.py on the GNN inference trajectory and pick up that trajectory with high collision rates as hard scenarios.
4. Run mpc.py on hard scenarios to get extended training labels.
5. Run train.py to train the new GNN model.
6. Run inference.py and calculate metrics.py to evaluate the new GNN model 
8. Note that we use generate_test_data.py to generate final test data with 8 to 20 vehicles to evaluate all the models (base model and models with hard data mining) in step 6. The final test data is not the same as the data mentioned in step 1,2,3 for picking up those hard scenarios.

Feel free to ask here if you have any other questions! ^_^

**Comment by sunminghao4536** [comment]
Thank you so much. I'll study first and ask you if I have any questions.

---- Replied Message ----
| From | Yining ***@***.***> |
| Date | 10/15/2024 21:00 |
| To | yininghase/multiagent-collision-mining ***@***.***> |
| Cc | sunminghao4536 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [yininghase/multiagent-collision-mining] Running code steps (Issue #1) |

Hello, thanks for your interest in this work. What you mentioned above is generally correct.

To be specific:

Run generate_test_data.py on 3 to 4 vehicles to get some random scenarios,
Run inference.py on these random scenarios with GNN model to get the inference trajectory from GNN.
Run calulate_metrics.py on the GNN inference trajectory and pick up that trajectory with high collision rates as hard scenarios.
Run mpc.py on hard scenarios to get extended training labels.
Run train.py to train the new GNN model.
Run inference.py and calculate metrics.py to evaluate the new GNN model
Note that we use generate_test_data.py to generate final test data with 8 to 20 vehicles to evaluate all the models (base model and models with hard data mining) in step 6. The final test data is not the same as the data mentioned in step 1,2,3 for picking up those hard scenarios.

Feel free to ask here if you have any other questions! ^_^

**Comment by sunminghao4536** [comment]
你刚才回答的标题六中产生的新的GNN模型是图片中所示的吗

![model](https://github.com/user-attachments/assets/2548dd79-9de0-4fbc-b9e4-f3dda96cf11d)

**Comment by sunminghao4536** [comment]
Hi, may I ask if the new GNN model you just replied to in heading 6 is the one shown in the picture?
![model](https://github.com/user-attachments/assets/dd2b14c3-97a6-4f9a-8c8d-dabe56528148)

**Comment by yininghase** [comment]
Hi, the baseline model is from another paper in this repo: https://github.com/yininghase/multi-agent-control, the model mentioned in heading 6 is the second one with extend hard data.
